In [1]:

import numpy as np
seats=np.zeros((5,8))



def display():
  print("Cinema Reservation")
  for rows in seats:
    print(rows)
    print("----------------------")

def theatre():
  reserved=False
  while reserved==False:
    row = int(input("Select your row number(0-4): "))
    col = int(input("Select your column number(0-7): "))
    if seats[row][col]==1:
      print("Oops,seat is already reserved")
    else:
      print("Yay! Seat is available!")
      seats[row][col]=1
      print("Reservation Complete!")
      reserved=True

def multipleseats():
  # s=int(input("How many seats do you want to book"))
  row = int(input("Select your row number(0-4): "))
  # col = int(input("Select your column number(0-7): "))
  col= input("Enter the list of seats you want to select, Ex: (0,1,2,3,4)")
  col=col.split(",")
  # for row in range(0,5):
  for c in range(len(col)):
      if (seats[row][int(col[c])]!=1):
        seats[row][int(col[c])]=1
        # seats.append(seats[row][int(col[c])])
        print("Reservation complete")
        continue
      else:
        print("No seats available")
        
      
def frontrow():
  for row in range(0,5):
    for col in range(0,8):
      if seats[row][col]==1:
        print("No seat is available")
        return False
      else:
        print("Yay! Seat is available!")
        seats[row][col]=1
        print("Reservation Complete!")
        print(f"Your seat is {seats[row][col]}")
        return True

def backrow():
  for row in range(4,-1,-1):
    for col in range(7,-1,-1):
      if seats[row][col]==1:
        print("No seat is available")
        return False
      else:
        print("Yay! Seat is available!")
        seats[row][col]=1
        print("Reservation Complete!")
        print(f"Your seat is {seats[row][col]}")
        return True

option=True
while option:
  
  print("Select a choice below:")
  print("1) Book a seat by row / column")
  print("2) Book multiple seats in a given row")
  print("3) Book seat in back row")
  print("4) Exit")
  option = input("Enter your selection: ")
  
  if option == '1':
    theatre()
    display()
  elif option == '2':
    display()
    multipleseats()
    display()
  elif option == '3':
    backrow()
    display()
  elif option=='4':
    option=False
    print("Exit!")
  
      
      
  
    
    

Select a choice below:
1) Book a seat by row / column
2) Book multiple seats in a given row
3) Book seat in back row
4) Exit
Enter your selection: 2
Cinema Reservation
[0. 0. 0. 0. 0. 0. 0. 0.]
----------------------
[0. 0. 0. 0. 0. 0. 0. 0.]
----------------------
[0. 0. 0. 0. 0. 0. 0. 0.]
----------------------
[0. 0. 0. 0. 0. 0. 0. 0.]
----------------------
[0. 0. 0. 0. 0. 0. 0. 0.]
----------------------
Select your row number(0-4): 1
Enter the list of seats you want to select, Ex: (0,1,2,3,4)2,3,4
Reservation complete
Reservation complete
Reservation complete
Cinema Reservation
[0. 0. 0. 0. 0. 0. 0. 0.]
----------------------
[0. 0. 1. 1. 1. 0. 0. 0.]
----------------------
[0. 0. 0. 0. 0. 0. 0. 0.]
----------------------
[0. 0. 0. 0. 0. 0. 0. 0.]
----------------------
[0. 0. 0. 0. 0. 0. 0. 0.]
----------------------
Select a choice below:
1) Book a seat by row / column
2) Book multiple seats in a given row
3) Book seat in back row
4) Exit
Enter your selection: 1
Select your row